### ISSUE TITLE
微信授权登录报错“无效用户”

### ISSUE THREAD

**Issue by jstar0** [suemor233/LostAndFound-weapp#2]
使用微信小程序开发工具的“真机测试”，给出报错
`WAServiceMainContext.js:1 [wxapplib]] backgroundfetch privacy fail {"errno":101,"errMsg":"private_getBackgroundFetchData:fail private_getBackgroundFetchData:fail:jsapi invalid request data"}`

`(in promise) MiniProgramError
Cannot read properties of undefined (reading 'token')
TypeError: Cannot read properties of undefined (reading 'token')
at (app-service.js:6835:18798)
at f (app-service.js:6845:437681)
at Generator._invoke (app-service.js:6845:437434)
at Generator.next (app-service.js:6845:438044)
at r (app-service.js:6845:431822)
at u (app-service.js:6845:432025)`

后端给出 `{ok: 0, message: "无效用户"}`

使用最新稳定版小程序工具，后端使用docker部署，设置openresty反向代理并配置ssl

**Comment by suemor233** [comment]
这个项目太久没更新，微信那边接口应该变了

最近一直在准备考试，比较忙，等我有时间再过来处理吧

**Comment by jstar0** [comment]
好的，非常谢谢！
如果可以的话，我们也想自己尝试一下更新这个接口，但是实在才疏学浅...如果方便的话，能否简单说一下大概怎么修改，指条明路，谢谢！！

**Comment by suemor233** [comment]
https://github.com/suemor233/LostAndFound-Core/blob/0409bf500019f3fb601c4823b9d28c1733d0cc95/src/modules/user/user.service.ts#L43-L51
